name: CD

on:
  workflow_dispatch:

permissions:
  id-token: write
  checks: write

env:
  PROJECT_NAME: github-traffic-insights
  PROJECT_FILE: src/FunctionApp/FunctionApp.csproj
  DOTNET_VERSION: 10.0.x

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        cache: true
        cache-dependency-path: '**/packages.lock.json'

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_FILE }} -c Release -o ./publish

    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: ${{ env.PROJECT_NAME }}
        package: ./publish
        remote-build: false
        enable-oryx-build: false
        respect-funcignore: true
      
    - name: Configure App Settings
      shell: bash
      run: |
        az functionapp config appsettings set \
          --name ${{ env.PROJECT_NAME }} \
          --resource-group ${{ env.PROJECT_NAME }} \
          --settings "TrafficIngestion__Schedule=0 0 0 * * *"
